name: tests

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.11.0
          cache: npm
      - run: npm ci
      - uses: actions/upload-artifact@v3
